- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        molecule: {}
  tasks:
    - name: Create a container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: sleep 1d            # чтобы контейнер не завершился сразу при создании
                                     # из-за отсутствия задач мы запускаем его с фоновым
                                     # процессом. Считаем, что нам достаточно 1 дня для тестов
        log_driver: json-file
      register: result
      loop: "{{ molecule_yml.platforms }}" # мы обращаемся к нашему входному файлу
                                           # и создаём все необходимые контейнеры

    - name: Fail if container is not running   # воспользуемся результатами создания контейнеров:
                                               # если код возврата отличный от 0 (0 - код успеха)
                                               # или контейнер не в запущенном состоянии,
                                               # то мы отправим его в файл-"заглушку"
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      ansible.builtin.include_tasks:
        file: tasks/create-fail.yml          
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.container.Name }}"

    - name: Add container to molecule_inventory 
                                                
      vars:                                # создадим структуру инвентори
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                hosts:
                  "{{ item.name }}":
                    ansible_connection: community.docker.docker
      ansible.builtin.set_fact:            # формируем инвентори для молекулы
                                           # путём объеденения структуры и данных
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Dump molecule_inventory            # создаём временный файл инвентори
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Force inventory refresh            # обновляем данные в инвентори
      ansible.builtin.meta: refresh_inventory

    - name: Fail if molecule group is missing  # проверяем, есть ли ли группа молекулы в инвентори
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
      run_once: true # noqa: run-once[task]
